<?php
/**
 * @file
 * The module file that explain how other module should integrate with the
 * doctor module.
 */

/**
 * Implements hook_doctor_listener_info().
 */
function doctor_example_doctor_listener_info() {
  return array(
    'doctor_example' => array(
      'callback' => 'doctor_example_doctor_listener_callback',
    ),
  );
}

/**
 * Doctor listener callback function.
 *
 * @param $data
 *  The un-serialized data listener item.
 */
function doctor_example_doctor_listener_callback($data) {
  $wrapper = $data['wrapper'];

  if ($wrapper->type() == 'node') {
    $params = array(
      '@title' => $wrapper->label(),
      '@user' => $wrapper->author->label(),
    );
    drush_print(dt('The user @user posted a node with the title: @title', $params));
  }
  else {
    $params = array(
      '@user' => $wrapper->author->label(),
    );
    drush_print(dt('The user @user posted a comment', $params));
  }
}

/**
 * Implements hook_node_insert().
 */
function doctor_example_node_insert($node) {
  $doctor = doctor_create(
    array(
      'wrapper' => entity_metadata_wrapper('node', $node),
    )
  );
  $doctor->save();
}

/**
 * Implements hook_comment_insert()
 */
function doctor_example_comment_insert($comment) {
  $doctor = doctor_create(
    array(
      'wrapper' => entity_metadata_wrapper('comment', $comment),
    )
  );
  $doctor->save();
}
